apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-app
  labels:
    app: food-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food-app
  template:
    metadata:
      labels:
        app: food-app
    spec:
      containers:
        - name: food-app
          image: abirami2006/food-app:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_USER
              value: root
            - name: DB_PASS
              value: "root"
            - name: DB_NAME
              value: food_order_db
